### ISSUE TITLE
Add `domain` column to server status and update script to use `domain` and `project` columns

### ISSUE THREAD

**Issue by Crola1702** [osrf/buildfarm-tools#68]
# Description

From comment in https://github.com/osrf/buildfarm-tools/pull/64#discussion_r1665137749

The reason behind this feature would be to stop relying on regex evaluations to get a job's domain. E.g.: https://github.com/osrf/buildfarm-tools/blob/317f8e5cc9b9adcf8683bcd25c3cb71125c811ca/database/scripts/lib/report_formatter.rb#L7-L9

# Tasks

- [x] Add domain column to buildfarmer.db
    * https://github.com/osrf/buildfarm-tools/pull/84
- [x] Update server status table with new information using databaseFetcher
    * https://github.com/osrf/buildfarm-tools-private/pull/50
- [ ] Update scripts to fetch the domain and project from sql queries instead
    * https://github.com/osrf/buildfarm-tools/pull/85
